--
SELECT * FROM TALUNO;

-- CONTATENANDO DUAS COLUNAS
SELECT Concat(COD_ALUNO,NOME) FROM TALUNO;

-- CONTATENANDO DUAS COLUNAS
SELECT COD_ALUNO||NOME FROM TALUNO;

SELECT COD_ALUNO||' - '||NOME FROM TALUNO;

-- COLOCA A PRIMEIRA LETRA DA PALAVRA EM MAIUSCULO
SELECT nome, InitCap(NOME) FROM TALUNO;

SELECT InitCap('LUIS DONIZETI PEREIRA') FROM DUAL;

-- ENCONTA A POSIÇÃO DA LETRA INDICADA
SELECT NOME, InStr(NOME,'R') FROM TALUNO;

-- CONTA A QTD DE CARACTERES
SELECT NOME, Length(NOME) FROM TALUNO;

-- TRANSFORMA TODAS AS LETRAS EM MINÚSCULAS
SELECT NOME, Lower(NOME) FROM TALUNO;

-- TRANSFORMA TODAS AS LETRAS EM MAIÚSCULAS
SELECT NOME, Upper(NOME) FROM TALUNO;

-- "L" - LEFT = ESQUERDA, ADICIONA CARACTERAES AS ESQUERDA
SELECT LPad(SALARIO, 8, '0') FROM TALUNO;

-- "R" - RIGTH = DIRETA, ADICIONA CARACTERAES AS DIREITA
SELECT RPad(SALARIO, 8, '0') FROM TALUNO;

SELECT RPad(SALARIO, 8, '#') FROM TALUNO;

-- APARTIR DE POSIÇÃO INICIAL, COPIA 'n' CARACTERES
SELECT NOME, SubStr(NOME,1,3) FROM TALUNO

SELECT NOME, SubStr(NOME,3,1) FROM TALUNO

SELECT NOME,SubStr(NOME,5,1) FROM TALUNO;

SELECT NOME,SubStr(NOME,Length(NOME),1) FROM TALUNO;

SELECT NOME,SubStr(NOME,3,Length(NOME)-3) FROM TALUNO;

-- SUBSTITUI UMA LETRA POR OUTRA
SELECT REPLACE(NOME,'R','$') FROM TALUNO;

SELECT REPLACE(Upper(NOME),'R','$') FROM TALUNO;




