
------------ DATA
SELECT * FROM DUAL;

-- SYSDATE RETORNA DATA/HORA DO SERVIDOR
SELECT SYSDATE FROM DUAL;

-- ROUND E TRUNC
SELECT Round(45.925, 2),  --45.93 (UTILIZA DUAS CASAS DECIMAIS, ARREDONDA PARA CIMA)
       Trunc(45.929, 2),  --45.92 (UTILIZA DUAS CASAS DECIMAIS, ARREDONDA PARA BAIXO)
       Mod(10, 2) AS RESTO_DIVISAO,
       Trunc(1.99),
       Trunc(1.99, 2)
FROM DUAL;

SELECT * FROM TCONTRATO;

-- FUNÇÕES DE DATA/HORA
SELECT DATA,
       SYSDATE,
       DATA + 5,
       SYSDATE = DATA AS DIF_DIAS,
       Trunc(SYSDATE - DATA)        AS DIAS,
       SYSDATE + 2 / 24             AS ADD_HORAS,
       SYSDATE + 15 / 1440          AS ADD_MINUTOS,
       SYSDATE + 30 / (3600 * 24)   AS ADD_SEGUNDOS
FROM TCONTRATO;

SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;

SELECT SYSDATE - DATA AS DIF_DIAS FROM TCONTRATO;

SELECT Trunc(SYSDATE - DATA) AS DIAS FROM TCONTRATO;

--SOMANDO HORAS EM UM DATA
SELECT SYSDATE, SYSDATE + 2 / 24 AS ADD_HORAS FROM TCONTRATO;

--SOMAR MINUTOS
SELECT SYSDATE, SYSDATE + 15 / 1440 AS ADD_MINUTOS FROM TCONTRATO;

--SOMAR SEGUNDOS
SELECT SYSDATE, SYSDATE + 30 / (3600 * 24) AS ADD_SEGUNDOS FROM TCONTRATO;

-- HORA FICA 00:00:00
SELECT SYSDATE, Trunc(SYSDATE) FROM DUAL;

--DIFERENÇA DE MESES ENTRE DATAS
SELECT MONTHS_BETWEEN(SYSDATE, SYSDATE-90) AS DIF_MES FROM DUAL;

--ADICIONA MESES
SELECT Add_Months(SYSDATE, 5) AS ADICIONA_MES_DATA FROM DUAL;

--PRÓXIMA DATA APARTIR DE UM DIA DA SEMANA (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY)
SELECT Next_Day(SYSDATE, 'WEDNESDAY') AS PROXIMA_QUARTA_DATA FROM DUAL;

--ULTIMO DIA DO MÊS CORRENTE
SELECT Last_Day(SYSDATE) AS ULTIMO_DIA_MES FROM DUAL;

--PRIMEIRO DIA DO PRÓXIMO MÊS
--ATÉ O DIA 15 DO MÊS PEGA O PRIMEIRO DIA DO MÊS ATUAL
--A PARTIR DO DIA 16 RETORNA O PRIMEIRO DIA DO PRÓXIMO MÊS
SELECT Round(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;

--PRIMEIRO DIA DO MÊS CORRENTE
SELECT Trunc(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_MES_CORRENTE FROM DUAL;



