
------- CAPÍTULO 05

SELECT * FROM TALUNO;

SELECT * FROM TCONTRATO;

-- PRODUTO CARTESIANO -> ERRADO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO;


UPDATE TALUNO SET NOME = 'MARCOS'
WHERE COD_ALUNO = 5

-- CORRETO, QUANDO UMA COLUNA EXISTE COM MESMO NOME EM MAIS DE UMA TABELA,
-- COLOCAR PREFIXO NA COLUNA
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;

-- ERRADO - COLUNA AMBIGUA (NÃO SABE QUAL A TABELA QUE COD_ALUNO PERDENCE)
SELECT COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL  --LINHA COM ERRO
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;

SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = COD_ALUNO;  --LINHA COM ERRO



