
UPDATE TCONTRATO SET DESCONTO = NULL
WHERE COD_CONTRATO = 4;

UPDATE TCONTRATO SET DESCONTO = NULL
WHERE COD_CONTRATO = 3;

SELECT Count(*) AS QTDE_REGISTROS
FROM TCONTRATO;

SELECT * FROM TCONTRATO;

--COUNT --> IGNORA NULOS
SELECT Count(DESCONTO)
FROM TCONTRATO;

SELECT * FROM TALUNO;

--QTDE DE REGISTROS COM ESTADO INFORMADO
SELECT Count(ESTADO) FROM TALUNO;

--QTDE DE REGISTROS POR ESTADO
SELECT Count(DISTINCT(ESTADO)) FROM TALUNO;

--QTDE DE REGISTROS POR ESTADO
SELECT ESTADO, Count(*)
FROM TALUNO
GROUP BY ESTADO;

--
SELECT Sum(DESCONTO),
       Avg(DESCONTO),
       Count(DESCONTO),
       Round(Avg(Nvl(DESCONTO,0)), 2)
FROM TCONTRATO;


SELECT * FROM TCONTRATO;

--TOTAL DE CONTRATO POR ESTADO E DATA
SELECT ALU.ESTADO, Trunc(CON.DATA) AS DATA,
       Sum(CON.TOTAL) TOTAL, Count(*) QTDE
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
GROUP BY ALU.ESTADO, Trunc(CON.DATA)
ORDER BY ALU.ESTADO, DATA DESC;

--TOTAL DE CONTRATO POR ESTADO
SELECT ALU.ESTADO,
       Sum(CON.TOTAL) TOTAL, Count(*) QTDE
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
GROUP BY ALU.ESTADO
ORDER BY ALU.ESTADO;

--HAVING - FILTAR COLUNA COM FUNÇÃO DE GRUPO
SELECT COD_ALUNO, Round(Avg(TOTAL),2) MEDIA
FROM TCONTRATO
WHERE COD_ALUNO > 0
HAVING Avg(TOTAL) > 500
GROUP BY COD_ALUNO
ORDER BY COD_ALUNO;

--
SELECT Trunc(DATA), Sum(TOTAL) TOTAL
FROM TCONTRATO
WHERE COD_CONTRATO > 0
GROUP BY Trunc(DATA)
HAVING Sum(TOTAL) > 500
ORDER BY TOTAL DESC;

--MEDIA MAIS ALTA POR ALUNO
SELECT Max(Avg(TOTAL))
FROM TCONTRATO
GROUP BY COD_ALUNO;

--SOMA DE SALARIOS PRO ESTADO
SELECT ESTADO, Sum(SALARIO) AS TOTAL
FROM TALUNO
GROUP BY ESTADO
ORDER BY 2 DESC;


