
-- CAPITULO 07 - SUB-CONSULTAS

--
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >=
  ( SELECT VALOR FROM TCURSO
    WHERE COD_CURSO = 3 );

--ERRADO (O SUB-SELECT SÓ PODE RETORNAR 1 LINHA NA SUBCONSULTA)
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >=
    ( SELECT VALOR FROM TCURSO
      WHERE VALOR > 500 );

SELECT * FROM TALUNO;

--TODOS AS ALUNOS DA MESMA CIDADE DO ALUNO 1,
--MENOS O ALUNO 1
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE CIDADE = ( SELECT CIDADE FROM TALUNO
                 WHERE COD_ALUNO = 1 )
AND COD_ALUNO <> 1;

--TODOS OS ALUNOS DA MESMA CIDADE E ESTADO DO ALUNO 1 MENOS O ALUNO 1
SELECT COD_ALUNO, NOME, CIDADE, ESTADO
FROM TALUNO
WHERE (CIDADE, ESTADO) =
          ( SELECT CIDADE, ESTADO FROM TALUNO
            WHERE COD_ALUNO = 1 )
AND COD_ALUNO <> 1;

--SOMA TODOS OS ITENS E MOSTRA SOMENTE CUJO O VALOR MÍNIMO SEJA MAIOR QUE O VALOR
--MÉDIO DOS CURSOS
SELECT COD_CURSO, Min(VALOR), Sum(VALOR), Count(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING Min(VALOR) >
        (SELECT Avg(VALOR) FROM TCURSO )
ORDER BY COD_CURSO;

