
SELECT * FROM TDESCONTO
ORDER BY CLASSE;

--SAVEPOINT (CRIA UM PONTO DE RESTAURAÇÃO)
SAVEPOINT upd_b;

UPDATE TDESCONTO SET
SUPERIOR = 88
WHERE CLASSE = 'B';

SAVEPOINT upd_a;

UPDATE TDESCONTO SET
SUPERIOR = 99
WHERE CLASSE = 'A';

--PONTO DE RESTAURAÇÃO
SAVEPOINT ins_Ok;

INSERT INTO TDESCONTO(CLASSE, INFERIOR, SUPERIOR)
VALUES ('&cla', &inf, &sup);

SELECT * FROM TDESCONTO
ORDER BY CLASSE;

--RESTAURANDO O SAVEPOINT
ROLLBACK TO SAVEPOINT ins_Ok;
ROLLBACK TO SAVEPOINT upd_a;
ROLLBACK TO SAVEPOINT upd_b;

--EXCLUIR TABELA
DROP TABLE TDESCONTO2;