
--CRIANDO UM TABELA
CREATE TABLE TESTE(
CODIGO INTEGER NOT NULL PRIMARY KEY,
DATA DATE DEFAULT SYSDATE
);

INSERT INTO TESTE (CODIGO) VALUES(1);
INSERT INTO TESTE (CODIGO, DATA) VALUES(2, '03/AUG/2013')

SELECT * FROM TESTE;

--TIPOS DE DADOS
VARCHAR2(10) -> 'MARCIO'
CHAR(10)     -> 'MARCIO'
NUMBER(5,2)  -> 999.99

--TABELAS CRIADAS PELO USUÁRIO - USER_TABLES (View)
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

--CRIANDO TABELA APARTIR DE UM RESULTADO
CREATE TABLE TCONTRATO_VIP AS
  SELECT * FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

--ADD COLUNA NA TABELA
ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2); --999,99

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2);

--ALTERAR COLUNA
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2) DEFAULT 0;

--RENOMEAR COLUNA
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

--EXCLUIR COLUNA
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

--EXCLUIR TABELA
DROP TABLE TCONTRATO_VIP;

--RENOMEAR TABELA
RENAME TCONTRATO TO TCONTRATO_TOP;

SELECT * FROM TCONTRATO_TOP;

RENAME TCONTRATO_TOP TO TCONTRATO;

SELECT * FROM TCONTRATO;
