
SELECT * FROM TCONTRATO;

--COMENTÁRIO NA TABELA
COMMENT ON TABLE TCONTRATO IS 'Informacoes de Contratos';

--COMENTÁRIO NA COLUNA DA TABELA
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do Contrato';

COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissao do Contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME='TCONTRATO';

SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME='TCONTRATO'

-- Desabilitar a coluna
ALTER TABLE TCONTRATO ADD TOTAL2 NUMERIC(8,2);

ALTER TABLE TCONTRATO SET UNUSED (TOTAL2);

--EXCLUIR COLUNAS NÃO USADA
ALTER TABLE TCONTRATO DROP USUSED COLUMNS


--TRUNCATE TABLE EXCUI TODOS OS REGISTROS DA TABELA
--NÃO TEM WHERE E NÃO TEM COMMIT/ROLLBACK
TRUNCATE TABLE TABELA;
