
CREATE SEQUENCE SEQ_ALUNO1
START WITH 60
--VALOR INICIAL
INCREMENT BY 5
--QTD A INCREMENTAR
MINVALUE 60
--VALOR MINIMO
MAXVALUE 100
--VALOR MAXIMO
NOCACHE
--NÃO GUARDA EM CACHE FAIXA DE VALORES
NOCYCLE;

INSERT INTO TALUNO(COD_ALUNO, NOME)
VALUES (SEQ_ALUNO1.NEXTVAL,'MASTER TRAINING'); --PRÓXIMO VALOR

INSERT INTO TALUNO(COD_ALUNO, NOME)
VALUES (SEQ_ALUNO1.NEXTVAL,'MASTER TRAINING2');

SELECT * FROM TALUNO;

COMMIT;

--MOSTRA AS SEQUENCIAS CRIADAS PELO USUÁRIOS
SELECT * FROM USER_SEQUENCES;

--MOSTRA A SEQUENCIA ATUAL
SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

--ALTERAR 0 VALOR MÁXIMO DA SEQUENCIA
ALTER SEQUENCE SEQ_ALUNO1 MAXVALUE 500;

--PARA ALTERAR O VALOR DE UMA SEQUENCIA, TEM QUE APAGAR A SEQUANCIA E CRIAR NOVAMENTE
DROP SEQUENCE SEQ_ALUNO1;
CREATE SEQUENCE SEQ_ALUNO1 START WITH 100;
