
--INDICES SECUNDARIOS
--CHAVE PRIMÁRIA É CONSIDERADO UM INDICE PRIMÁRIO

-- O INDICE É CRIADO PARA TER GANHO DE PERFORMANCE, PORÉM PODE OCASIONAR LENTIDÃO
-- NO INSERT, UPDATE E DELETE

SELECT NOME FROM TALUNO
WHERE NOME LIKE'%A%';  --F9

CREATE INDEX IND_TALUNO_NOME1 ON TALUNO(NOME);

SELECT NOME FROM TALUNO
WHERE NOME LIKE '%MA%'; --F9

--
CREATE INDEX IND_TALU_NOMECIDADE ON TALUNO(NOME, CIDADE);

SELECT NOME,CIDADE FROM TALUNO
WHERE NOME LIKE '%A%' AND CIDADE LIKE '%A%';

SELECT * FROM USER_INDEXES;

--APAGANDO UM INDICE
DROP INDEX IND_TALU_NOMECIDADE;


--SINOMIMOS: CRIA UM APELIDO PARA UMA TABELA
CREATE SYNONYM ALU FOR TALUNO;

SELECT * FROM ALU;
