
-- INDICANDO APENAS AS COLUNAS QUE SERÃO VISTAS
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO;


-- ADICIONADO APELIDO NAS COLUNAS
SELECT COD_ALUNO AS "Código", NOME AS "Nome do Aluno"
FROM TALUNO;


-- DISTINCT RETIRA LINHAS DUPLICADAS, TODAS COLUNAS TEM QUE SER IGUAIS
SELECT CIDADE FROM TALUNO;

SELECT DISTINCT CIDADE FROM TALUNO;


-- NÃO AGRUPA POIS COD_ALUNO TEM VALOR DIFERENTE PARA CADA LINHA
SELECT DISTINCT CIDADE, COD_ALUNO
FROM TALUNO
ORDER BY CIDADE;


-- Round PERMITE DEFINIR O NUMERO DE CASAS DECIMAIS QUE SERÃO MOSTRADAS
SELECT NOME AS CURSO,
               VALOR,
               VALOR/CARGA_HORARIA,
               Round(VALOR/CARGA_HORARIA,2) AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA; -- APELIDO DE COLUNA SÓ FUNCIONA EM ORDER BY


SELECT * FROM TCONTRATO;


UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO = 4;


-- CALCULO COM COLUNA = NULL O RESULTADO = NULL
SELECT COD_CONTRATO,
       TOTAL,
       DESCONTO,
       TOTAL+DESCONTO
FROM TCONTRATO;


-- Nvl TRATA O TIPO DA COLUNA, SE A COLUNA FOR NULL IRÁ RETORNAR 0
SELECT COD_CONTRATO,
       DESCONTO,
       Nvl(DESCONTO,0),
       TOTAL,
       TOTAL + Nvl(DESCONTO,0) AS TOTAL_MAIS_DESCONTO
FROM TCONTRATO;


-- CONCATENAÇÃO DE COLUNAS
SELECT COD_ALUNO || ' - ' || NOME || ' // ' || CIDADE AS ALUNO
FROM TALUNO
ORDER BY COD_ALUNO;


  INTEGER         - 1, 2  -- NUMERO INTEIRO --> NUMBER(38)

  NUMBER(5,2)         - 999,99
  NUMERIC(5,2)        - 999,99

  DATE                - '10/03/2011 00:00:00'

  VARCHAR(10)         -- É UM SINÔNIMO DE VARCHAR2
  VARCHAR2(10)        - 'LUIS'
  CHAR(10)            - 'LUIS'